#!/bin/sh
cd /opt/cannybots/runtime/nodered/cannybox/
hciconfig hci0 down
sleep 2
hciconfig hci0 up
exec /usr/bin/node --max-old-space-size=128 ./bin/www
exec /usr/local/bin/node --max-old-space-size=128 ./bin/www

