#!/bin/sh
cd /opt/cannybots/runtime/nodered/cannybox/
hciconfig hci0 down
sleep 2
hciconfig hci0 up
if [ -e /usr/bin/node ]; then
exec /usr/bin/node --max-old-space-size=128 ./bin/www
else
exec /usr/local/bin/node --max-old-space-size=128 ./bin/www
fi

